---
title: "Camera trapping for wildlife research - chapter 5"
output: html_notebook
---

## Introduction
One challenge we face is in getting our data into a format in which we can use some other people's code for our analysis (or at least see how other people's code works and modify to suit our needs).  Here's I'm going to work through the case study in Chapter 5 of Camera Trapping for Wildlife Research and work as well with one of our own sample files to try and push ours into the same format as CTFWR.

To do so, I need the R scripts they provide on their book [dropbox folder](https://www.dropbox.com/sh/5w4y6u7uq2mc2i3/AADjdBCrN_7tAg-UHAbhf8sFa?dl=0).




```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

