---
title: "Dealing with different identifications of the same animal"
output: html_notebook
---

Because we host our project on the zooniverse, it is possible to have multiple people score each event, which means we may not get the same answers for each event in terms of species id, behavior, etc.

To that end, we need a way to check which events have differences in their identifications of species and of e.g. behaviors.  Once those events are identified, we need an efficient way to go back to those events and make a final appraisal of their contents.

The following bunch of R scripts takes the flattened classfication file produced by running the *Flatten-zooniverse-NoCoWild.Rmd* scripts and does the following:  

1. Identify which events have more than one classification
2. For those events with more than 1 classification,

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

