---
title: "Overview"
author: "Erika"
date: "6/4/2019"
output: html_document
---

##Introduction
This document is designed to provide an overview of the steps of working through zooniverse code to prepare it for analysis and then to do the analysis.

##Data
A sample data set, based on the [North Country Wild Phase 1 project](https://www.zooniverse.org/lab/8607) at the [Zooniverse](https://www.zooniverse.org) is found in this directory and is called "sampledata.csv".

##Workflow
The basic workflow for processing these data prior to analysis involves the following steps:

1. Download classification file from zooniverse.
2. Isolate the data from a single workflow number and workflow version so that all fields are compatible.
3. Parse the annotations column (JSON format).
4. Parse the subject_data column (JSON format).
5. Merge the annotations & subject_data to a data frame for data analysis via a join command.
6. Identify and rectify events for which there is conflict in the species identification.

The end result should be a flat file with species correctly identified that is ready to be wrangled into the proper format for another set of R processing steps for priliminary data analysis.

The R code to accomplish steps 2 - 5 above is called *Flatten-zooniverse-NoCoWild.Rmd* and is located in this directory.


